#!/usr/bin/env python3

from typing import List

import sys
import os
import re

os.chdir("stdlib")

class Method:
    name: str
    arguments: int
    returns: bool

class Class:
    name: str
    methods: List[Method]

re_class = re.compile("SB_CLASS\(([^)]+)\)")
re_method = re.compile("SB_METHOD_([0-9]+)\(([^)]+)\)")

classes: List[Class] = list()

for file in os.scandir("."):
    if file.name == "Runtime_generated.hpp":
        continue
    header = open(file, "r")
    
    cls: Class = None
    mtd: Method = None
    for line in header.readlines():
        if cls is None:
            m = re_class.match(line)
            if m is not None:
                cls = Class()
                cls.name = m.group(1)
                cls.methods = []
                classes.append(cls)
        else:
            m = re_method.match(line)
            if m is not None:
                mtd = Method()
                mtd.arguments = int(m.group(1))
                mtd.name = m.group(2)
                mtd.returns = True
                cls.methods.append(mtd)
                print(cls.name + "." + mtd.name + "(" +
                    str(mtd.arguments) + ")", file=sys.stderr)
            elif "SB_VOID" in line:
                mtd.returns = False
    
    header.close()


indent = ""
def write(line: str):
    print(indent + line)

print(
'''// Generated by generate_runtime_list.py
#include "Runtime.hpp"'''
)

for cls in classes:
    write("#include \"" + cls.name + ".hpp\"")
indent = "    "

print(
"""
namespace SmallBasic {
void register_builtin() {
    static bool did_register_builtin = false;
    if (did_register_builtin) {
        return;
    }
    did_register_builtin = true;
"""
)

for cls in classes:
    write("Class $" + cls.name + "(\"" + cls.name + "\");")
    for mtd in cls.methods:
        write("$" + cls.name + ".register_method({ \"" + mtd.name + "\", " +
              cls.name + "::dispatch_" + mtd.name + ", " + str(mtd.arguments) +
              ", " + ("true" if mtd.returns else "false") + " });")
    write("Runtime::register_class($" + cls.name + ");")
    if classes[-1] is not cls:
        write("")

print(
"""}
}"""
)